AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: x20153104RP

Resources:

  # Lambda Function
  TransmitTupleLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TransmitTupleData
      Runtime: java8.al2
      AutoPublishAlias: live
      MemorySize: 512
      Handler: transmission.TransmitTuple::transmitTupleData
      CodeUri: target/lambda.zip
      Role: arn:aws:iam::250738637992:role/service-role/20153104TransmitTupleRole
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1 
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:18"
      Policies:
        - CloudWatchLambdaInsightsExecutionRolePolicy
 
  #Autoscaler for Lambda function       
  LambdaScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 1
      MaxCapacity: 100
      ResourceId: !Sub function:${TransmitTupleLambda}:live
      RoleARN: arn:aws:iam::250738637992:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_x20153104-Project_e1b9b118f911a7ce
      ScalableDimension: lambda:function:ProvisionedConcurrency
      ServiceNamespace: lambda
    DependsOn: TransmitTupleLambdaAliaslive 
    
  # Lambda Autoscaler Configuration
  MyTargetTrackingScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: utilization
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref LambdaScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 0.70 
        PredefinedMetricSpecification:
          PredefinedMetricType: LambdaProvisionedConcurrencyUtilization  