AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: x20153104RP

Resources:

  TransmitTupleLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TransmitTupleData
      Runtime: java8
      MemorySize: 512
      Handler: transmission.TransmitTuple::transmitTupleData
      CodeUri: target/lambda.zip
      Role: arn:aws:iam::250738637992:role/Lambda-Execution-Role